name: Unzip and commit to root

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Descomprime el ZIP en la raíz
      - name: Unzip to root
        run: |
          unzip -o Streammmmm.zip -d ./

      # 3. Muestra archivos extraídos
      - name: List files
        run: ls -R .

      # 4. Configura Git para hacer commit
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzipped Streammmmm.zip into root" || echo "No changes to commit"
          git push
